### ISSUE TITLE
Initial Javascript Runtime Client SDK

### ISSUE THREAD

**Issue by kostko** [oasisprotocol/oasis-bridge#2]
Should use TypeScript and we should make sure to structure things nicely (see #1 for the current -- very WIP -- structure of the Go Client SDK and the Rust Runtime SDK). The plan is to make this into a general runtime and consensus layer Javascript SDK.

* [x] Explore grpc-web for exposing our gRPC interfaces to Javascript
* [x] Types
  * [x] CBOR serialization
  * [x] Big integers and tokens (`Quantity`, `BaseUnit`, `Denomination`)
  * [x] Signatures
    * [x] Ed25519
    * [x] Secp256k1
  * [x] Addresses
  * [x] Transactions
* [x] Signers in a modular way similar to Oasis Core so there can be different signer implementations (e.g., Ledger, browser extension, constant mnemonic etc.)
  * [x] In-memory signer based on a constant mnemonic (useful for development)
  * [x] Ledger (currently ParaTime transactions are not supported, but we can still add a signer)

Different runtimes will have different other types so it would be good to think about how to expose that to the various client SDKs. Polkadot uses type introspection via RPC (see Polkadot.js), we may want to do something similar eventually (probably not for the initial version).
